### ISSUE TITLE
Search is glitchy

### ISSUE THREAD

**Issue by thilojaeggi** [KODDevYouTube/InstagramApp#5]
If I enter an exact username it shows nothing. Really weird.

**Comment by Bhismydv** [comment]
> If I enter an exact username it shows nothing. Really weird.

fragment_search.xml -

Makes your RecyclerView, height and width  "match_parent"      

 <androidx.recyclerview.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@id/bar"
        android:id="@+id/recycler_view"/>

**Comment by Zarkex** [comment]
It shows entries but the search is not working correctly. It shows users but they are not relevant to the search query, funnily in my Code for the Databasereference it doesn't say "S:" it says "Path:" I'm guessing this is the issue but I haven't found a fix yet.

**Comment by Bhismydv** [comment]
show me code...
