### ISSUE TITLE
Username not being shown in search fragment

### ISSUE THREAD

**Issue by adiig7** [KODDevYouTube/InstagramApp#6]
In search fragment the username and full name is not being shown only follow/following button shows up. Though when I click on username it jumps to profile section so it's working properly. @Bhismydv Can you have a look at it please?
![Screenshot_1585477945](https://user-images.githubusercontent.com/54351909/77846876-bf9e8b00-71d6-11ea-805a-cf5ebfd5aad2.png)

**Comment by Bhismydv** [comment]
can you attach the file also

**Comment by Bhismydv** [comment]
then I properly check and understand what was the problem going on

**Comment by Bhismydv** [comment]
you can also mail me (bhismydv2912)

**Comment by Bhismydv** [comment]
can you use slack

**Comment by adiig7** [comment]
Code of user activity.java


        package com.example.insta.Adapter;

        import android.content.Context;
        import android.content.Intent;
        import android.content.SharedPreferences;
        import android.view.LayoutInflater;
        import android.view.View;   
        import android.view.ViewGroup;
        import android.widget.Button;
        import android.widget.TextView;

        import androidx.annotation.NonNull;
        import androidx.fragment.app.FragmentActivity;
        import androidx.recyclerview.widget.RecyclerView;

        import com.bumptech.glide.Glide;
        import com.example.insta.Fragment.ProfileFragment;
        import com.example.insta.MainActivity;
        import com.example.insta.Model.User;
        import com.example.insta.R;
        import com.google.firebase.auth.FirebaseAuth; 

        import com.google.firebase.auth.FirebaseUser;
        import com.google.firebase.database.DataSnapshot;
        import com.google.firebase.database.DatabaseError;

        import com.google.firebase.database.DatabaseReference;
        import com.google.firebase.database.FirebaseDatabase;
        import com.google.firebase.database.ValueEventListener;

        import java.util.HashMap;
        import java.util.List;

        import de.hdodenhof.circleimageview.CircleImageView;

         import static android.content.Context.MODE_PRIVATE;

           public class UserAdapter extends RecyclerView.Adapter<UserAdapter.ImageViewHolder> {

    private Context mContext;
    private List<User> mUsers;
    private boolean isFragment;

    private FirebaseUser firebaseUser;

    public UserAdapter(Context context, List<User> users, boolean isFragment){
        mContext = context;
        mUsers = users;
        this.isFragment = isFragment;
    }

    @NonNull
    @Override
    public UserAdapter.ImageViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(mContext).inflate(R.layout.user_item, parent, false);
        return new UserAdapter.ImageViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull final UserAdapter.ImageViewHolder holder, final int position) {

        firebaseUser = FirebaseAuth.getInstance().getCurrentUser();

        final User user = mUsers.get(position);

        holder.btn_follow.setVisibility(View.VISIBLE);
        isFollowing(user.getId(), holder.btn_follow);

        holder.username.setText(user.getUsername());
        holder.fullname.setText(user.getFullname());
        Glide.with(mContext).load(user.getImageurl()).into(holder.image_profile);

        if (user.getId().equals(firebaseUser.getUid())){
            holder.btn_follow.setVisibility(View.GONE);
        }

        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (isFragment) {
                    SharedPreferences.Editor editor = mContext.getSharedPreferences("PREFS", MODE_PRIVATE).edit();
                    editor.putString("profileid", user.getId());
                    editor.apply();

                    ((FragmentActivity) mContext).getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container,
                            new ProfileFragment()).commit();
                } else {
                    Intent intent = new Intent(mContext, MainActivity.class);
                    intent.putExtra("publisherid", user.getId());
                    mContext.startActivity(intent);
                }
            }
        });

        holder.btn_follow.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (holder.btn_follow.getText().toString().equals("follow")) {
                    FirebaseDatabase.getInstance().getReference().child("Follow").child(firebaseUser.getUid())
                            .child("following").child(user.getId()).setValue(true);
                    FirebaseDatabase.getInstance().getReference().child("Follow").child(user.getId())
                            .child("followers").child(firebaseUser.getUid()).setValue(true);

                    addNotification(user.getId());
                } else {
                    FirebaseDatabase.getInstance().getReference().child("Follow").child(firebaseUser.getUid())
                            .child("following").child(user.getId()).removeValue();
                    FirebaseDatabase.getInstance().getReference().child("Follow").child(user.getId())
                            .child("followers").child(firebaseUser.getUid()).removeValue();
                }
            }

        });
    }

    private void addNotification(String userid){
        DatabaseReference reference = FirebaseDatabase.getInstance().getReference("Notifications").child(userid);

        HashMap<String, Object> hashMap = new HashMap<>();
        hashMap.put("userid", firebaseUser.getUid());
        hashMap.put("text", "started following you");
        hashMap.put("postid", "");
        hashMap.put("ispost", false);

        reference.push().setValue(hashMap);
    }

    @Override
    public int getItemCount() {
        return mUsers.size();
    }

    public class ImageViewHolder extends RecyclerView.ViewHolder {

        public TextView username;
        public TextView fullname;
        public CircleImageView image_profile;
        public Button btn_follow;

        public ImageViewHolder(View itemView) {
            super(itemView);

            username = itemView.findViewById(R.id.username);
            fullname = itemView.findViewById(R.id.fullname);
            image_profile = itemView.findViewById(R.id.image_profile);
            btn_follow = itemView.findViewById(R.id.btn_follow);
        }
    }

    private void isFollowing(final String userid, final Button button){

        final FirebaseUser firebaseUser = FirebaseAuth.getInstance().getCurrentUser();

        DatabaseReference reference = FirebaseDatabase.getInstance().getReference()
                .child("Follow").child(firebaseUser.getUid()).child("following");
        reference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if (dataSnapshot.child(userid).exists()){
                    button.setText("following");
                } else{
                    button.setText("follow");
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
        }
       }

Code of user_item.xml

          <?xml version="1.0" encoding="utf-8"?>
      <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:padding="8dp"
    android:layout_height="wrap_content">

    <de.hdodenhof.circleimageview.CircleImageView
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:id="@+id/image_profile"
        android:src="@mipmap/ic_launcher"/>

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_toRightOf="@id/image_profile"
        android:layout_toEndOf="@id/image_profile"
        android:layout_marginLeft="5dp"
        android:layout_centerVertical="true"
        android:orientation="vertical"
        android:layout_marginStart="5dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="username"
            android:id="@+id/username"
            android:maxLines="1"
            android:textStyle="bold"
            android:textColor="@color/colorPrimaryDark"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/fullname"
            android:maxLines="1"
            android:text="Full Name"/>

    </LinearLayout>

    <Button
        android:layout_width="wrap_content"
        android:layout_height="30dp"
        android:background="@drawable/button_background"
        android:visibility="gone"
        android:id="@+id/btn_follow"
        android:textColor="@color/colorPrimary"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_centerVertical="true"/>
</RelativeLayout>``

**Comment by Bhismydv** [comment]
send me the   search_fragment

**Comment by Bhismydv** [comment]
user model class also

**Comment by adiig7** [comment]
Code of search_fragment.java



        package com.example.insta.Fragment;

        import android.app.DownloadManager;
      import android.content.SharedPreferences;
        import android.os.Bundle;

         import androidx.annotation.NonNull;
        import androidx.fragment.app.Fragment;
          import androidx.recyclerview.widget.LinearLayoutManager;
         import androidx.recyclerview.widget.RecyclerView;

           import android.text.Editable;
        import android.text.TextWatcher;
          import android.view.LayoutInflater;
         import android.view.View;
            import android.view.ViewGroup;
          import android.widget.EditText;

            import com.example.insta.Adapter.UserAdapter;
            import com.example.insta.Model.User;
           import com.example.insta.R;
            import com.google.firebase.auth.FirebaseAuth;
             import com.google.firebase.auth.FirebaseUser;
             import com.google.firebase.database.DataSnapshot;
              import com.google.firebase.database.DatabaseError;
             import com.google.firebase.database.DatabaseReference;
            import com.google.firebase.database.FirebaseDatabase;
              import com.google.firebase.database.Query;
            import com.google.firebase.database.ValueEventListener;

               import java.util.ArrayList;
              import java.util.List;

              public class SearchFragment extends Fragment {

              private RecyclerView recyclerView;
              private UserAdapter userAdapter;
    private List<User> userList;

    EditText search_bar;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_search, container, false);

        recyclerView = view.findViewById(R.id.recycler_view);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));

        search_bar = view.findViewById(R.id.search_bar);

        userList = new ArrayList<>();
        userAdapter = new UserAdapter(getContext(), userList, true);
        recyclerView.setAdapter(userAdapter);

        readUsers();
        search_bar.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {

            }

            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
                searchUsers(charSequence.toString().toLowerCase());
            }

            @Override
            public void afterTextChanged(Editable editable) {

            }
        });

        return view;
        }

       private void searchUsers(String s){
        Query query = FirebaseDatabase.getInstance().getReference("Users").orderByChild("username")
                .startAt(s)
                .endAt(s+"\uf8ff");

        query.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                userList.clear();
                for (DataSnapshot snapshot : dataSnapshot.getChildren()){
                    User user = snapshot.getValue(User.class);
                    userList.add(user);
                }

                userAdapter.notifyDataSetChanged();
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
           });
          }

         private void readUsers() {

        final FirebaseUser firebaseUser = FirebaseAuth.getInstance().getCurrentUser();
        DatabaseReference reference = FirebaseDatabase.getInstance().getReference("Users");

        reference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if (search_bar.getText().toString().equals("")) {
                    userList.clear();
                    for (DataSnapshot snapshot : dataSnapshot.getChildren()) {
                        User user = snapshot.getValue(User.class);

                        userList.add(user);

                    }

                    userAdapter.notifyDataSetChanged();
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
           });
           }
           }

**Comment by Bhismydv** [comment]
xml part

**Comment by adiig7** [comment]
XML search_fragment      

                 <?xml version="1.0" encoding="utf-8"?>
             <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
               android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:context=".Fragment.SearchFragment">

             <com.google.android.material.appbar.AppBarLayout
                 android:layout_width="match_parent"
                 android:layout_height="wrap_content"
               android:id="@+id/bar"
                 android:background="?android:attr/windowBackground">

    <androidx.appcompat.widget.Toolbar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?android:attr/windowBackground"
        android:id="@+id/toolbar">

      <ImageView
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:src="@drawable/ic_search"/>

      <EditText
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:background="@android:color/transparent"
          android:layout_marginLeft="10dp"
          android:id="@+id/search_bar"
          android:hint="Search..."
          android:layout_marginStart="10dp" />

    </androidx.appcompat.widget.Toolbar>
            </com.google.android.material.appbar.AppBarLayout>

                 <androidx.recyclerview.widget.RecyclerView
                     android:layout_width="match_parent"
                       android:layout_height="wrap_content"
                      android:layout_below="@id/bar"
                        android:id="@+id/recycler_view"/>

               </RelativeLayout>

**Comment by adiig7** [comment]
User model class code 

              package com.example.insta.Model;

             public class User {
             private String id;
             private String username;
               private String fullname;
               private String imageurl;
               private String bio;

    public User(String id, String username, String fullname, String imageurl, String bio) {
        this.id = id;
        this.username = username;
        this.fullname = fullname;
        this.imageurl = imageurl;
        this.bio = bio;
    }

    public User() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }
       }

**Comment by Bhismydv** [comment]
> ```
> XML search_fragment      
> 
>              <?xml version="1.0" encoding="utf-8"?>
>          <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>          xmlns:tools="http://schemas.android.com/tools"
>            android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             tools:context=".Fragment.SearchFragment">
> 
>          <com.google.android.material.appbar.AppBarLayout
>              android:layout_width="match_parent"
>              android:layout_height="wrap_content"
>            android:id="@+id/bar"
>              android:background="?android:attr/windowBackground">
> 
> <androidx.appcompat.widget.Toolbar
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content"
>     android:background="?android:attr/windowBackground"
>     android:id="@+id/toolbar">
> 
>   <ImageView
>       android:layout_width="wrap_content"
>       android:layout_height="wrap_content"
>       android:src="@drawable/ic_search"/>
> 
>   <EditText
>       android:layout_width="match_parent"
>       android:layout_height="wrap_content"
>       android:background="@android:color/transparent"
>       android:layout_marginLeft="10dp"
>       android:id="@+id/search_bar"
>       android:hint="Search..."
>       android:layout_marginStart="10dp" />
> 
> </androidx.appcompat.widget.Toolbar>
>         </com.google.android.material.appbar.AppBarLayout>
> 
>              <androidx.recyclerview.widget.RecyclerView
>                  android:layout_width="match_parent"
>                    android:layout_height="wrap_content"
>                   android:layout_below="@id/bar"
>                     android:id="@+id/recycler_view"/>
> 
>            </RelativeLayout>
> ```

try match_parent in recyclerview height  and width

**Comment by adiig7** [comment]
still not working, its the same.

**Comment by Bhismydv** [comment]
your firebase stored data properly

**Comment by adiig7** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/54351909/77849265-faf58580-71e7-11ea-9e10-49ef041b3d46.png)

**Comment by Bhismydv** [comment]
your problem is much complicated because the follow button show but profile not shown.

Rather than both are in the same layout

**Comment by adiig7** [comment]
![Screenshot_1585485667](https://user-images.githubusercontent.com/54351909/77849366-c209e080-71e8-11ea-9014-a454ea48c86a.png)
username is not being shown here too above the post....what should I do now?

**Comment by Bhismydv** [comment]
upload your full project on Github after that I can clone your project and check hole project

**Comment by Bhismydv** [comment]
make a repository and upload it

**Comment by adiig7** [comment]
Done!! Have a look.

**Comment by Bhismydv** [comment]
ok then I contact you tomorrow

**Comment by Bhismydv** [comment]
with solution

**Comment by adiig7** [comment]
ok sure thank you.

**Comment by Bhismydv** [comment]
hey, I think I find the issue

**Comment by Bhismydv** [comment]
![WhatsApp Image 2020-03-30 at 1 19 08 AM](https://user-images.githubusercontent.com/52397602/77859063-e2f02700-7224-11ea-94f2-58e7d58c0188.jpeg)

**Comment by Bhismydv** [comment]
here you can see

**Comment by Bhismydv** [comment]
you can give the wrong reference

**Comment by adiig7** [comment]
sorry but I'm still not getting and how do I resolve it?

**Comment by Bhismydv** [comment]
Go to Firebase Console->Select Project->Storage(click on the Storage)->and copy download Url not storage location

**Comment by Bhismydv** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/52397602/77859224-bf79ac00-7225-11ea-9da4-42de4de34067.png)

**Comment by Bhismydv** [comment]
see

**Comment by Bhismydv** [comment]
you can paste the wrong reference

**Comment by Bhismydv** [comment]
try it

**Comment by adiig7** [comment]
I copied the download url and pasted in there in hashmap but its still the same

**Comment by Bhismydv** [comment]
send me download url

**Comment by adiig7** [comment]
https://firebasestorage.googleapis.com/v0/b/insta-d9274.appspot.com/o/placeholder.png?alt=media&token=12387951-7b10-4d59-9e25-461055817f2c

**Comment by Bhismydv** [comment]
delete all the data from firebase (Authentication,users and whatever which can store data) and uninstall app

**Comment by Bhismydv** [comment]
then rebuild your project and install the app

**Comment by Bhismydv** [comment]
start with a fresh user

**Comment by Bhismydv** [comment]
it's too late for me ok bye and I will see in morning

**Comment by Bhismydv** [comment]
update me ok

**Comment by Bhismydv** [comment]
i will sends you a pull request add this and try

**Comment by Bhismydv** [comment]
check the commit changes
